### ISSUE TITLE
Weird weighted grade calculation

### ISSUE THREAD

**Issue by ualch9** [team-llambda/gradebook-backend-ondevice#1]
Consider the following:
```xml
<GradeCalculationSummary>
    <AssignmentGradeCalc Type="Participation" Weight="20%" Points="118.00" PointsPossible="125.00" WeightedPct="18.88%" CalculatedMark="A"/>
    <AssignmentGradeCalc Type="Classroom Assignments" Weight="25%" Points="572.00" PointsPossible="580.00" WeightedPct="24.65%" CalculatedMark="A"/>
    <AssignmentGradeCalc Type="Projects" Weight="45%" Points="463.00" PointsPossible="500.00" WeightedPct="41.67%" CalculatedMark="A"/>
    <AssignmentGradeCalc Type="TOTAL" Weight="100%" Points="1,153.00" PointsPossible="1,205.00" WeightedPct="94.60%" CalculatedMark="A"/>
    <AssignmentGradeCalc Type="Section Assessment" Weight="10%" Points="0.00" PointsPossible="0.00" WeightedPct="0.00%" CalculatedMark="0"/>
</GradeCalculationSummary>
```

| Type | Weight | Points | Points Possible | Weighted Percentage | Calculated Mark |
|---|:--:|:--:|:--:|:--:|:--:|
| Participation | 20% | 118.00 | 125.00 | 18.88% | A |
| Classroom Assignments | 25% | 572.00 | 580.00 | 24.65% | A |
| Projects | 45% | 463.00 | 500.00 | 41.67% | A |
| Section Assessment | 10% | 0.00 | 0.00 | 0.00% | 0 |
| Expected TOTAL | 100% | 1153.00 | 1,205.00 | 85.20% | B |
|-|-|-|-|-|-|
| Actual TOTAL  | 100% | 1,153.00 | 1,205.00 | 94.60% | A |

Issue: How is the `Weighted Percentage` 94.6% (when it should be 85.20%)?

**Comment by darkterbear** [comment]
The **Section Assessment** category has no points in it; therefore, it is not counted in the weighted calculation. The weights of the other categories scale so that the total is 100%.

In this case:
Sum of weights = 20% + 25% + 45% = 90%
Scaling factor = 1/0.9 = 1.111...

New weights:
Participation: 20% * 1.111 = **22.222**%
Classroom Assignments: 25% * 1.111 = **27.778**%
Projects: 45% * 1.111 = **50**%

New weighted percentages
Participation: 18.88% * 1.111 = **20.978**%
Classroom Assignments: 24.65% * 1.111 = **27.389**%
Projects: 41.67% * 1.111 = **46.3**%
**Total: 94.6%**
